#!/usr/bin/python 

import json

from pymandrake import Plugin

def analyze(fmeta):
	fm = json.loads(fmeta)
	return '{"Hello from Python" : "%s"}' % fm['Filepath']

def main():

	plug = Plugin('HelloWorldPython')
	plug.listen(analyze)

if __name__ == '__main__':
	main()
