#!/usr/bin/python

import json
import yara
import sys

from argparse import ArgumentParser
from pymandrake import Plugin

RULES_FILE = 'rules.yar'
RULES = None

def analyze(fmeta):
	'''Analyze a file utilizing YARA'''

	fm = json.loads(fmeta)

	analysis = dict()
	analysis['errors'] = []

	try:
		matches = RULES.match(fm.get('Filepath'))
	except:
		matches = []
		analysis['matches'] = matches
		analysis['errors'].append('error performing yara analysis')
		return json.dumps(analysis)

	analysis['matches'] = [str(match) for match in matches]

	return json.dumps(analysis)

def main():

	global RULES_FILE
	global RULES

	parser = ArgumentParser(description='Mandrake plugin for YARA')
	parser.add_argument('--rules_file', type=str, 
						default=RULES_FILE,
						help='file where yara rules are loaded from')
	args = parser.parse_args()

	plug = Plugin('YARA')

	RULES_FILE = args.rules_file
	try:
		RULES = yara.compile(RULES_FILE)
	except yara.Error:
		plug.log('Unable to compile yara rules file %s' % (RULES_FILE))

	plug.listen(analyze)

if __name__ == '__main__':
	main()